[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "buff"
version = "0.1.0"
description = "Buff project utilities and API"
authors = [
    { name="Na'Sir Miller" }
]

[tool.setuptools]
packages = ["buff"]